# Generated by Django 5.0.6 on 2024-09-07 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(help_text='Rate from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Album_name',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='realese_date',
            new_name='release_date',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
